[package]
name = "dawnjection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dawnjection-codegen ={ path = "../core-codegen" }
eyre = "0.6.8"
futures = "0.3.28"